### ISSUE TITLE
Shape mismatch while running sanity check

### ISSUE THREAD

**Issue by pwz266266** [suinleelab/vit-shapley#1]
Hi there, I'm really interested in this paper. But when I try to run the code with settings in `traning_classifier.md`.
I'm running it on Windows 11 and I got the following error:
```
Traceback (most recent call last):
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\sacred\experiment.py", line 312, in run_commandline
    return self.run(
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\sacred\experiment.py", line 276, in run
    run()
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\sacred\run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\sacred\config\captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "C:\Users\pwz26\OneDrive\Desktop\vit-shapley\main.py", line 488, in main
    trainer.fit(model_to_train, datamodule=datamodule)
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1199, in _run
    self._dispatch()
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1289, in run_stage
    return self._run_train()
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1311, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1375, in _run_sanity_check
    self._evaluation_loop.run()
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\pytorch_lightning\loops\base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\pytorch_lightning\loops\base.py", line 140, in run
    self.on_run_start(*args, **kwargs)
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 86, in on_run_start
    self._dataloader_iter = _update_dataloader_iter(data_fetcher, self.batch_progress.current.ready)
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\pytorch_lightning\loops\utilities.py", line 121, in _update_dataloader_iter
    dataloader_iter = enumerate(data_fetcher, batch_idx)
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 199, in __iter__
    self.prefetching(self.prefetch_batches)
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 258, in prefetching
    self._fetch_next_batch()
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 300, in _fetch_next_batch
    batch = next(self.dataloader_iter)
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\torch\utils\data\dataloader.py", line 652, in __next__
    data = self._next_data()
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\torch\utils\data\dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\torch\utils\data\dataloader.py", line 1373, in _process_data
    data.reraise()
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\torch\_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\pytorch_lightning\utilities\auto_restart.py", line 474, in _capture_metadata_collate
    data = default_collate(samples)
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\torch\utils\data\_utils\collate.py", line 160, in default_collate
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\torch\utils\data\_utils\collate.py", line 160, in <dictcomp>
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "C:\Users\pwz26\anaconda3\envs\vit_shapley\lib\site-packages\torch\utils\data\_utils\collate.py", line 141, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 160, 213] at entry 0 and [3, 160, 211] at entry 1
```

Am I missing any settings? The config.py looks like:
```
@ex.config
def config():
    # Stage Setting
    stage = "classifier"  ## (classifier, surrogate, explainer, classifier_masked)

    # Wandb setting
    wandb_project_name = "default_wandb_project_name"
    exp_name = "ImageNette_classifier_vit_base_patch16_224_1e-5_train"

    # Environment Setting
    log_dir = "results"
    per_gpu_batch_size = 64  # you should define this manually with per_gpu_batch_size=#
    gpus_classifier = [0]
    gpus_surrogate = None
    gpus_explainer = None
    num_nodes = 1
    num_workers = 4
    precision = 16

    # Seed Setting
    seed = 0

    # Dataset Setting
    datasets = "ImageNette"  # (ImageNette, MURA)
    dataset_location = "C:/Users/pwz26/Downloads/imagenette2-320"
    explanation_location_train = None
    explanation_mask_amount_train = None
    explanation_mask_ascending_train = None
    explanation_location_val = None
    explanation_mask_amount_val = None
    explanation_mask_ascending_val = None
    explanation_location_test = None
    explanation_mask_amount_test = None
    explanation_mask_ascending_test = None

    output_dim = 10
    target_type = "multiclass"  # ("binary", "multiclass", "multilabel")
    img_channels = 3
    test_data_split = "test"  # (test, val, train)
    transforms_train = {
        "Resize": {
            "apply": False,
            "height": 256,
            "width": 256
        },
        "RandomResizedCrop": {
            "apply": False,
            "size": 224,
            "scale": [
                0.8,
                1.2
            ]
        },
        "CenterCrop": {
            "apply": False,
            "height": 224,
            "width": 224
        },
        "VerticalFlip": {
            "apply": False,
            "p": 0.5
        },
        "HorizontalFlip": {
            "apply": False,
            "p": 0.5
        },
        "ColorJitter": {
            "apply": False,
            "brightness": 0.2,
            "contrast": 0.2,
            "saturation": 0.1,
            "hue": 0.1,
            "p": 0.8
        },
        "Normalize": {
            "apply": True
        },
    }  # the final resize transform should be modified to fit the input dim of the model being trained.
    transforms_val = {
        "Resize": {
            "apply": False,
            "height": 256,
            "width": 256
        },
        "CenterCrop": {
            "apply": False,
            "height": 224,
            "width": 224
        },
        "Normalize": {
            "apply": False
        },

    }  # the final resize transform should be modified to fit the input dim of the model being trained.
    transforms_test = {
        "Resize": {
            "apply": False,
            "height": 256,
            "width": 256
        },
        "CenterCrop": {
            "apply": False,
            "height": 224,
            "width": 224
        },
        "Normalize": {
            "apply": False
        },

    }  # the final resize transform should be modified to fit the input dim of the model being trained.

    # Classifier Model Setting
    classifier_masked_mask_location = "pre-softmax"
    classifier_backbone_type = "vit_base_patch16_224"
    classifier_enable_pos_embed = True
    classifier_download_weight = True
    classifier_load_path = None

    # Surrogate Model Setting
    surrogate_mask_location = None
    surrogate_backbone_type = None  # "deit_small_patch16_224"
    surrogate_download_weight = True
    surrogate_load_path = None

    # Explainer Model Setting
    explainer_num_mask_samples_epoch = 0
    explainer_num_mask_samples = 32
    explainer_paired_mask_samples = True
    explainer_normalization = None
    explainer_normalization_class = None
    explainer_link = None
    explainer_residual = []
    explainer_activation = None

    explainer_efficiency_lambda = 0
    explainer_efficiency_class_lambda = 0
    explainer_freeze_backbone = True

    explainer_head_num_attention_blocks = 1
    explainer_head_num_mlp_layers = 3
    explainer_head_mlp_layer_ratio = 4
    explainer_head_include_cls = True
    explainer_norm = True

    explainer_backbone_type = None
    explainer_download_weight = True
    explainer_load_path = None

    # Dataloader Setting
    batch_size = 64  # this is a desired batch size; pl trainer will accumulate gradients when per step batch is smaller.

    # Training Setting
    checkpoint_metric = "accuracy"
    optim_type = "Adamw"
    loss_weight = 1.0
    learning_rate = 1e-5
    weight_decay = 1e-5
    decay_power = "cosine"
    grad_clipping = 1.0
    max_epochs = 25
    warmup_steps = 500

    unfreeze_after = None
    unfreeze_after_gradual = False

    val_check_interval = 1.0
    test_only = False
    resume_from = None
    fast_dev_run = False
```

It seems to happen during sanity check stage, may you please help me resolving this? Many thanks.

**Comment by chanwkimlab** [comment]
Hi, thank you so much for your interest in our work. 

As the `vit_base_patch16_224` model takes an image of size 224x224 as input, the dataset module should scale the image data into the size. I don't get why the image was preprocessed into a tensor of size 3x160x211. Could you please let me know the command line you have run? I would like to confirm that you are using the ImageNette dataset and associated settings.

Best,
Chanwoo

**Comment by pwz266266** [comment]
Thank you so much for your quick reply! I just figured it out: I wasn't setting the named configs correctly. My apologies (first time using `sacred`). Not sure why the error was reported as `3x160x211` though, a bit confusing.
